#!/bin/bash

showhelp=0

function isCtlArg {
    local me=`grep -e ^- <<< "$1"`
    local ret=0

    if [ "$me" == '' ]; then
        echo "nope"
    else
        echo "yep"
    fi
}

if [ $# != 0 ]; then 

    # echo " "

    seditor="${SHELL}"
    layout="h"

    first=1
    cnt=$#

    command="tmux new ";

    if [ $(isCtlArg "$1") == "nope" ]; then 
        command=$command"-s'$1' "
        session_name="$1"
        ((first=2)) 
    fi

    # create Session
    #--------------------------------------------------------------------------
    # echo "--------------------------------------------";
    # echo " start session "
    # echo "--------------------------------------------";
    command=$command"-d '$seditor' "
    # echo $command
    eval $command

    if [[ -z ${session_name} ]]; then 
        session_name=`tmux ls -F '#{session_created} #{session_name}' | sort | tail -n 1 | cut -d ' ' -f 2-`
        # echo "session created: " $session_name
    fi

    command='tmux ' 

    # echo "--------------------------------------------";
    # echo " process commands "
    # echo "--------------------------------------------";

    panes=0
    mode=0      # 0 = set window name
    layout="h"

    cnt=$#

    for (( i=$first; i<=$cnt; i++ )); do

        eval "arg=\"\${$i}\""
        # echo ">   arg $i is: $arg"

        if [[ $(isCtlArg "$arg") == "yep" ]]; then 
            # echo ">>  is Ctl command"

            if [[ "$arg" == "-w" ]]; then
                # echo ">>> create new window" 
                if [[ $panes -gt 1 ]]; then 
                    # echo ">>> has $panes panes"
                    if [[ "$layout" == "v" ]]; then
                        # echo ">>> layout vertical"
                        command=$command" \; select-layout -t '$session_name' even-horizontal"
                    else
                        # echo ">>> layout horizontal"
                        command=$command" \; select-layout -t '$session_name' even-vertical"
                    fi
                fi

                command=$command" \; new-window -t '$session_name' '$editor' "
                ((mode=0))
                ((panes=0))
                layout="h"

            elif [[ "$arg" == "-v" ]]; then
                layout="v"

            elif [[ "$arg" == "-c" ]]; then
                ((mode=1))
            fi
        else
            if [[ $mode == 0 ]]; then
                # echo ">>> Rename window"
                command=$command" \; rename-window -t '$session_name' '"$arg"'"
            elif [[ $mode == 1 ]]; then
                if [[ $panes == 0 ]]; then
                    command=$command" \; respawn-pane -k -t '$session_name:' '"$arg"'"                                              
                else
                    command=$command"\; split-pane -t '$session_name' '$arg' "    
                fi
                ((panes++))
            fi
        fi
    done
    
    # echo "--------------------------------------------"
    # echo " Lets Gooooo !! "
    # echo "--------------------------------------------"
    # echo $command
    
    command=$command" \; select-window -t '$session_name:0' "

    # echo $command
    eval $command

    if [ -n "${TMUX}" ]; then
        tmux switch-client -t "${session_name}"
    else
        tmux attach -t "${session_name}"
    fi
 
else

#===============================================================================
# help text, if the function is called with any kind of parameter
#===============================================================================
echo "usage: $(basename $0) [sessionname] [windowname] [-v] [-c command1 command2] ...

                    [-w windowname1] 
                        [-v] [-c command1 command2]... 

                    [-w windowname2] 
                        [-v] [-c command1 command2]... 

       Parameters:

            sessionname     if provided, tmux will use this as session identifier
                            (Default: given by tmux)

            windowname      defines, what the first window in the new session 
                            is called (Default: given by tmux)

            -w windowname   to start a new window

            -v              to define, that all splits for this window should have
                            a vertical layout (else horizontal)

            command1, command2, ...
                            the commands, that should be executed under this 
                            specific window
                            0(If no command is given, the current shell will be used)

"
fi

