#!/bin/bash

if [ -z $1 ]; then 

    editor='nvim'

    command="tmux new ";
    name="${TMUX_SESSION_NAME}"

    echo $TMUX

#===============================================================================
# Session-Name
#===============================================================================
    if [ -n "${TMUX_SESSION_NAME}" ]; then 
        command=$command"-s'${TMUX_SESSION_NAME}' "
    else
        echo "no sessioname"
    fi
    command=$command" "

#===============================================================================
# Handhle nesting
#===============================================================================
    command=$command" -d '$editor'"
    eval $command

    session_name=`tmux ls -F '#{session_created} #{session_name}' | sort | tail -n 1 | awk -F' ' '{print $2}'`
    echo "session created: " $session_name

    command='tmux ' 


#===============================================================================
# Alway open an editor
#===============================================================================
    command=$command" rename-window -t '$session_name' 'editor' "

#===============================================================================
# Function to create the different Window Groups 
#===============================================================================
function makeAWindow {

    echo "call makeAWindow" $1 $2

    cmd="";
    x=1
    eval 'ev="${TMUX_SESSION_'$1'_'$x'}"' 
    while [ -n "$ev" ]; do 
        echo $2" command $x: $ev"

        if [ $x -eq 1 ]; then
            cmd=$cmd" \; new-window -t '$session_name' '$ev' \; rename-window -t '$session_name' '"$2"'"    
        else
            cmd=$cmd" \; split-pane -t '$session_name' '$ev'"    
        fi

        ((x+=1))
        eval 'ev="${TMUX_SESSION_'$1'_'$x'}"' 
    done 

    if [ $x -gt 1 ]; then
        eval 'ev="${TMUX_SESSION_'$1'_VERTICAL}"'
        if [ -z "$ev" ]; then
            cmd=$cmd" \; select-layout -t '$session_name' even-vertical"
        else
            cmd=$cmd" \; select-layout -t '$session_name' even-horizontal"
        fi
    fi

    command=$command$cmd
}


#===============================================================================
# Build all the other windows
#===============================================================================
makeAWindow "LOG" "logs" 
makeAWindow "SERVER" "server" 
makeAWindow "DATABASE" "database" 


#===============================================================================
# select the editor window and start tmuxing
#===============================================================================
    command=$command" \; select-window -t '$session_name:editor' "

    #echo $command
    eval $command

    if [ -n "${TMUX}" ]; then
        tmux switch-client -t "${session_name}"
    else
        tmux attach -t "${session_name}"
    fi

else
#===============================================================================
# help text, if the function is called with any kind of parameter
#===============================================================================
    echo "usage: 
    To give your session a custom name.
        export TMUX_SESSION_NAME=[what to name the tmux session]

    Each of the follwoing windows can contain as many panes, as you like.
    just make sure the numbering from 1 to x is without breaks

    To open a logging window with x panes:
        export TMUX_SESSION_LOG_1=[command for first log]
        ...
        export TMUX_SESSION_LOG_x=[command for the xth log]
       
    To open a server window with x panes:
        export TMUX_SESSION_SERVER_1=[command for first server]
        ...
        export TMUX_SESSION_SERVER_x=[command for the xth server]

    To open a database window with x panes:
        export TMUX_SESSION_DATABASE_1=[command for first database]
        ...
        export TMUX_SESSION_DATABASE_x=[command for the xth database]
   
    To any of these 3 into a vertical layout define 

        export TMUX_SESSION_LOG_VERTICAL=1
        export TMUX_SESSION_SERVER_VERTICAL=1
        export TMUX_SESSION_DATABASE_VERTICAL=1
    resepectively.

    after everything is set up. call 

        $0
    "
fi

